cabal-version:      3.0
name:               deep-learning-in-haskell
version:            0.1.0.0
synopsis:           Deep Learning in Haskell
-- description:
license:            MIT
license-file:       LICENSE
author:             Gabriel Emannuel
maintainer:         gabriel.emannuel.gama.andrade@gmail.com
-- copyright:
category:           Math
build-type:         Simple
extra-doc-files:    CHANGELOG.md
-- extra-source-files:

data-files:         data/iris.csv, data/mnist_train.csv, data/mnist_test.csv

common warnings
    ghc-options: -Wall -threaded -O2 -rtsopts -with-rtsopts=-N

library
    import:           warnings
    exposed-modules:  
        ActivationFunction,
        Architeture,
        Convolutional,
        Model,
        Layers,
        LossFunctions,
        Utils
    -- other-modules: Potato 
    -- other-extensions:
    build-depends:    
        base ^>=4.20.2.0,
        parallel >= 3.2 && < 4,
        deepseq >= 1.4 && < 2,
        random
    hs-source-dirs:   src
    default-language: Haskell2010

test-suite deep-learning-in-haskell-test
    import:           warnings
    default-language: Haskell2010
    other-modules:
        IrisTest,
        MnistTest 
    -- other-extensions:
    type:             exitcode-stdio-1.0
    hs-source-dirs:   test
    main-is:          Main.hs
    build-depends:
        base ^>=4.20.2.0,
        deep-learning-in-haskell,
        HUnit
